---
version: 2
sources:
- name: "qa_team.qa_database"
  database: "qa_team"
  schema: "qa_database"
  tables:
  - name: "store"
    columns: []
    type: "table"
- name: "hive_metastore.arun123"
  database: "hive_metastore"
  schema: "arun123"
  config:
    enabled: true
  tables:
  - name: "million_records"
    description: "A comprehensive dataset containing demographic information, including\
      \ names, ages, IDs, and cities, useful for various analytical purposes."
    quoting:
      identifier: true
    columns:
    - name: "ID"
      description: "Unique identifier for each record in the dataset"
      dataType:
        type: "Bigint"
    - name: "Name"
      description: "The name of the individual"
      dataType:
        type: "String"
    - name: "Age"
      description: "The age of the individual"
      dataType:
        type: "Bigint"
    - name: "City"
      description: "The city where the individual resides"
      dataType:
        type: "String"
    type: "table"
