---
version: 2
models:
- name: "model_p1_custom_object_data"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p1_source"
  database: "hive_metastore"
  schema: "arun123"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p1_post_custom_object_data_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p1_pre_custom_object_data_0"
    tags:
    - "prophecy_temp"
