---
version: 2
models:
- name: "model_p2_Aggregate_1"
  tags:
  - "prophecy_temp"
- name: "model_p2_Filter_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p2_source"
  database: "database"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p2_post_Filter_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p2_post_Aggregate_1_0"
    tags:
    - "prophecy_temp"
