---
version: 2
sources:
- name: "hive_metastore.arun123"
  database: "hive_metastore"
  schema: "arun123"
  config:
    enabled: true
  tables:
  - name: "model"
    description: "Customer order history and lifetime value data, providing insights\
      \ into customer behavior and value to the business."
    quoting:
      identifier: true
    columns:
    - name: "customer_id"
      description: "Unique identifier for the customer"
      dataType:
        type: "Bigint"
    - name: "first_name"
      description: "First name of the customer"
      dataType:
        type: "String"
    - name: "last_name"
      description: "Last name of the customer"
      dataType:
        type: "String"
    - name: "first_order"
      description: "Date of the customer's first order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      description: "Date of the most recent order placed by the customer"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      description: "Total count of orders placed by the customer"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      description: "The total value of purchases made by the customer over their lifetime"
      dataType:
        type: "Double"
    type: "table"
- name: "hive_metastore.asadas"
  database: "hive_metastore"
  schema: "asadas"
  config:
    enabled: true
  tables:
  - name: "test5672"
    description: "Country-specific data capturing various metrics, aiding in regional\
      \ analysis and insights."
    quoting:
      identifier: true
    columns:
    - name: "country_code"
      description: "Code representing the country of the data entry"
      dataType:
        type: "String"
    - name: "1"
      description: "A numeric identifier associated with the record."
      dataType:
        type: "Integer"
    - name: "scv"
      description: "A string representing a specific value related to the dataset."
      dataType:
        type: "String"
    type: "table"
