name: sql_external_project_main
description: ''
version: 0.0.1
author: arunsharma+admin@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/job101:
    name: job101
    description: ''
    fabricUID: 4331
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-06-25 04:56:37'
    author: arunsharma+admin@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-06-25 04:55:24'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2025-06-25 04:55:36'
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: arunsharma+admin@prophecy.io
  createdAt: '2025-06-25 04:55:24'
dependencies: []
projectDependencies:
  '22363':
    projectUID: 22363
    projectName: ProphecyDatabricksSqlBasics
    repositoryPath: gitUri=https://github.com/prophecy-io/databricks-sql-basics&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-06-25 04:54:55'
flags:
  shouldAddDefaultDependenciesIfAbsent: false
pipelineConfigurations: {}
sqlOrchestratorPipelines:
  .prophecy/metadata/sqlorchestratorpipeline/p101:
    name: p101
    schema: null
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - .prophecy/ide/pipelines/p101.json
    - pipelines/p101.py
    createdAt: '2025-06-25 04:56:24'
sqlBusinessApps: {}
