---
version: 2
models:
- name: "model_ghghhj_Aggregate_1"
  tags:
  - "prophecy_temp"
- name: "model_ghghhj_Deduplicate_1"
  tags:
  - "prophecy_temp"
- name: "model_ghghhj_SetOperation_1"
  tags:
  - "prophecy_temp"
- name: "model_ghghhj_Aggregate_2"
  tags:
  - "prophecy_temp"
- name: "model_ghghhj_Filter_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_ghghhj_source"
  database: "hive_metastore"
  schema: "default"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_ghghhj_post_Aggregate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_ghghhj_post_Aggregate_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_ghghhj_post_Deduplicate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_ghghhj_post_Filter_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_ghghhj_post_SetOperation_1_0"
    tags:
    - "prophecy_temp"
