---
version: 2
models:
- name: "model_pipeline11_Aggregate_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline11_Deduplicate_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline11_source"
  database: "hive_metastore"
  schema: "arun123"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline11_post_Aggregate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline11_post_Deduplicate_1_0"
    tags:
    - "prophecy_temp"
