name: this_is_Sql_project_2
description: ''
version: 0.0.1
author: arunsharma+admin@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/j1:
    name: j1
    description: ''
    fabricUID: 4331
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-07-04 20:22:18'
    author: arunsharma+admin@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-07-04 20:19:14'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/m1:
    name: m1
    schema: null
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - models/m1.sql
    - .prophecy/ide/models/m1.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2025-07-04 20:20:15'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/f1:
    name: f1
    macroType: expression
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - macros/f1.sql
    - .prophecy/ide/macros/f1.json
    - macros/macros.yml
    createdAt: '2025-07-04 20:21:26'
  .prophecy/metadata/sqlmacros/g1:
    name: g1
    macroType: query
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - macros/g1.sql
    - .prophecy/ide/macros/g1.json
    - macros/macros.yml
    - gems/g1.py
    createdAt: '2025-07-04 20:21:20'
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2025-07-04 20:19:59'
  .prophecy/metadata/sqlmacros/prophecy_tmp_source:
    name: prophecy_tmp_source
    macroType: expression
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - macros/prophecy_tmp_source.sql
    - .prophecy/ide/macros/prophecy_tmp_source.json
    createdAt: '2025-07-04 20:20:09'
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: arunsharma+admin@prophecy.io
  createdAt: '2025-07-04 20:19:14'
dependencies: []
projectDependencies:
  '22363':
    projectUID: 22363
    projectName: ProphecyDatabricksSqlBasics
    repositoryPath: gitUri=https://github.com/prophecy-io/databricks-sql-basics&subPath=
    version: 0.0.11.dev0
    isDefault: true
    author: null
    createdAt: '2025-07-04 20:18:54'
flags:
  shouldAddDefaultDependenciesIfAbsent: false
pipelineConfigurations: {}
sqlOrchestratorPipelines:
  .prophecy/metadata/sqlorchestratorpipeline/p1:
    name: p1
    schema: null
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - .prophecy/ide/pipelines/p1.json
    - pipelines/p1.py
    createdAt: '2025-07-04 20:20:09'
sqlBusinessApps:
  .prophecy/metadata/sqlbusinessapp/app1:
    name: app1
    schema: null
    description: null
    author: arunsharma+admin@prophecy.io
    files:
    - apps/app1.json
    createdAt: '2025-07-04 20:21:44'
    sqlOrchestrationPipelineName: p1
