---
version: 2
models:
- name: "m1"
  columns:
  - name: "PROJECTS"
    dataType:
      type: "Array"
  - name: "EMPLOYEE_ID"
    dataType:
      type: "Number"
  - name: "DEPARTMENT_ID"
    dataType:
      type: "Number"
  - name: "EMPLOYEE_NAME"
    dataType:
      type: "String"
  - name: "HIRE_DATE"
    dataType:
      type: "Date"
  - name: "SALARY"
    dataType:
      type: "Float"
  - name: "SUPERVISOR"
    dataType:
      type: "Object"
  - name: "TEAM_EFFORT"
    dataType:
      type: "Array"
  - name: "PERFORMANCE"
    dataType:
      type: "Object"
  tests: []
