name: scala_project
description: ''
version: gjgh
author: arunsharma+sp@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: scalaproject
  parentArtefactID: arunsharmaspprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2025-05-28 09:51:11'
pipelines:
  pipelines/ewrwe:
    name: ewrwe
    description: ''
    author: arunsharma+sp@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-05-28 09:56:08'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs:
  jobs/o9kl:
    name: o9kl
    description: ''
    fabricUID: 7252
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-05-28 09:56:56'
    author: arunsharma+sp@prophecy.io
    models: []
    sqlProjects: []
  jobs/job2:
    name: job2
    description: ''
    fabricUID: 7252
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-05-28 09:57:08'
    author: arunsharma+sp@prophecy.io
    models: []
    sqlProjects: []
  jobs/job3:
    name: job3
    description: ''
    fabricUID: 7252
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-05-28 09:57:35'
    author: arunsharma+sp@prophecy.io
    models: []
    sqlProjects: []
  jobs/job4:
    name: job4
    description: ''
    fabricUID: 7252
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-05-28 09:57:51'
    author: arunsharma+sp@prophecy.io
    models: []
    sqlProjects: []
  jobs/job5:
    name: job5
    description: ''
    fabricUID: 7252
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-05-28 09:58:00'
    author: arunsharma+sp@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-05-28 09:51:11'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-05-28T09:51:11.787286Z'
  name: plibMaven
  version: 8.10.0-SNAPSHOT
  id: '1309277897'
  createdAt: '2025-05-28T09:51:11.787286Z'
  type: plibMaven
projectDependencies:
  '39':
    projectUID: 39
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_39.git&subPath=
    version: 0.2.6.2
    isDefault: true
    author: null
    createdAt: '2025-05-28 09:50:56'
  '40':
    projectUID: 40
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_40.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2025-05-28 09:50:56'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
