---
version: 2
models:
- name: "model_pipeline1_Aggregate_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline1_Deduplicate_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline1_FlattenSchema_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline1_Aggregate_2"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline1_source"
  database: "hive_metastore"
  schema: "arun123"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline1_post_Aggregate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline1_post_Aggregate_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline1_post_Deduplicate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline1_post_FlattenSchema_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline1_pre_Aggregate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline1_pre_Deduplicate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline1_pre_Deduplicate_2_0"
    tags:
    - "prophecy_temp"
