---
version: 2
models:
- name: "model_pipeline2_Deduplicate_2"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline2_source"
  database: "hive_metastore"
  schema: "arun123"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline2_post_Deduplicate_2_0"
    tags:
    - "prophecy_temp"
