---
version: 2
models:
- name: "model_p10_Filter_0"
  tags:
  - "prophecy_temp"
- name: "model_p10_Except_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p10_source"
  database: "hive_metastore"
  schema: "arun123"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p10_post_Except_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p10_post_Filter_0_0"
    tags:
    - "prophecy_temp"
