---
version: 2
models:
- name: "model_p4_WindowFunction_0"
  tags:
  - "prophecy_temp"
- name: "model_p4_Deduplicate_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p4_source"
  database: "hive_metastore"
  schema: "default"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p4_post_Deduplicate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p4_post_WindowFunction_0_0"
    tags:
    - "prophecy_temp"
