---
version: 2
models:
- name: "model_grtgrtgrt_m1_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_grtgrtgrt_source"
  database: "database"
  schema: "default"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_grtgrtgrt_post_m1_1_0"
    tags:
    - "prophecy_temp"
