---
version: 2
models:
- name: "model_sftp_pipeline_Filter_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_sftp_pipeline_source"
  database: "tanmay"
  schema: "default"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_sftp_pipeline_post_Filter_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sftp_pipeline_pre_Reformat_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sftp_pipeline_pre_Reformat_2_0"
    tags:
    - "prophecy_temp"
