---
version: 2
models:
- name: "model_pipeline1_Reformat_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline1_Reformat_2"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline1_source"
  database: "hive_metastore"
  schema: "arun123"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline1_post_Reformat_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline1_post_Reformat_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline1_post_SFTPSource_0_0"
    tags:
    - "prophecy_temp"
