---
version: 2
models:
- name: "model_p13_WindowFunction_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p13_source"
  database: "database"
  schema: "default"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p13_post_WindowFunction_1_0"
    tags:
    - "prophecy_temp"
