---
version: 2
models:
- name: "model_pipeline3_Aggregate_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline3_Deduplicate_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline3_Except_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline3_source"
  database: "hive_metastore"
  schema: "arun123"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline3_post_Aggregate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline3_post_Deduplicate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline3_post_Except_1_0"
    tags:
    - "prophecy_temp"
