---
version: 2
models:
- name: "model_p12_Aggregate_0"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p12_source"
  database: "database"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p12_post_Aggregate_0_0"
    tags:
    - "prophecy_temp"
