---
version: 2
models:
- name: "model_pipeline23_selected_records"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline23_source"
  database: "Tanmay"
  schema: "default"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline23_post_selected_records_0"
    tags:
    - "prophecy_temp"
