name: spark_project_external
description: ''
version: 0.0.1
author: arunsharma+admin@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: sparkprojectexternal
  parentArtefactID: teamprophecyjjfh7
  buildSystem: wheel
  author: null
  createdAt: '2025-07-04 20:56:46'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: arunsharma+admin@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-07-04 20:56:46'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs:
  jobs/job1:
    name: job1
    description: ''
    fabricUID: 4205
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-07-04 21:00:35'
    author: arunsharma+admin@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-07-04 20:56:46'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-07-04T20:56:46.047092Z'
  name: plibMaven
  version: 8.11.0-SNAPSHOT
  id: '729795468'
  createdAt: '2025-07-04T20:56:46.047092Z'
  type: plibMaven
- modifiedAt: '2025-07-04T20:56:46.047092Z'
  name: plibPypi
  version: 2.0.4
  id: '780614926'
  createdAt: '2025-07-04T20:56:46.047092Z'
  type: plibPypi
projectDependencies:
  '42':
    projectUID: 42
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_42.git&subPath=
    version: 0.2.46
    isDefault: true
    author: null
    createdAt: '2025-07-04 20:56:21'
  '43':
    projectUID: 43
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_43.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-07-04 20:56:21'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
