---
version: 2
models:
- name: "model_p7_Aggregate_0"
  tags:
  - "prophecy_temp"
- name: "model_p7_FlattenSchema_1"
  tags:
  - "prophecy_temp"
- name: "model_p7_Union_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p7_source"
  database: "database"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p7_post_Union_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p7_post_FlattenSchema_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p7_post_Aggregate_0_0"
    tags:
    - "prophecy_temp"
