---
version: 2
sources:
- name: "main.information_schema"
  database: "main"
  schema: "information_schema"
  tables: []
- name: "qa_team.qa_database"
  database: "qa_team"
  schema: "qa_database"
  tables:
  - name: "employees"
    description: "Employee information including titles and managerial relationships,\
      \ supporting organizational structure insights."
    columns:
    - name: "TITLE"
      description: "The job title of the employee"
      dataType:
        type: "String"
    - name: "EMPLOYEE_ID"
      description: "Unique identifier for each employee"
      dataType:
        type: "Double"
    - name: "MANAGER_ID"
      description: "The ID of the employee's manager"
      dataType:
        type: "Double"
    type: "table"
  - name: "customer"
    description: "Customer profile data capturing essential details such as demographics,\
      \ contact information, and sales history."
    columns:
    - name: "C_CUSTOMER_SK"
      description: "Unique identifier for each customer in the system"
      dataType:
        type: "Double"
    - name: "C_CUSTOMER_ID"
      description: "Unique identifier for each customer"
      dataType:
        type: "String"
    - name: "C_CURRENT_CDEMO_SK"
      description: "Current demographic key representing customer characteristics."
      dataType:
        type: "Double"
    - name: "C_CURRENT_HDEMO_SK"
      description: "The current household demographic key for the customer"
      dataType:
        type: "Double"
    - name: "C_CURRENT_ADDR_SK"
      description: "The unique identifier for the customer's current address"
      dataType:
        type: "Double"
    - name: "C_FIRST_SHIPTO_DATE_SK"
      description: "The key representing the date of the customer's first shipment."
      dataType:
        type: "Double"
    - name: "C_FIRST_SALES_DATE_SK"
      description: "The date when the customer made their first purchase."
      dataType:
        type: "Double"
    - name: "C_SALUTATION"
      description: "The salutation used for addressing the customer"
      dataType:
        type: "String"
    - name: "C_FIRST_NAME"
      description: "The first name of the customer"
      dataType:
        type: "String"
    - name: "C_LAST_NAME"
      description: "The last name of the customer"
      dataType:
        type: "String"
    - name: "C_PREFERRED_CUST_FLAG"
      description: "Indicates whether the customer is a preferred customer."
      dataType:
        type: "String"
    - name: "C_BIRTH_DAY"
      description: "Day of the customer's birth"
      dataType:
        type: "Double"
    - name: "C_BIRTH_MONTH"
      description: "The month in which the customer was born"
      dataType:
        type: "Double"
    - name: "C_BIRTH_YEAR"
      description: "The year of birth of the customer"
      dataType:
        type: "Double"
    - name: "C_BIRTH_COUNTRY"
      description: "Country of birth of the customer"
      dataType:
        type: "String"
    - name: "C_LOGIN"
      description: "The login identifier for the customer"
      dataType:
        type: "String"
    - name: "C_EMAIL_ADDRESS"
      description: "Email address of the customer"
      dataType:
        type: "String"
    - name: "C_LAST_REVIEW_DATE"
      description: "The date when the customer last reviewed their account"
      dataType:
        type: "String"
    type: "table"
  - name: "call_center"
    columns: []
    type: "view"
- name: "hive_metastore.arun123"
  database: "hive_metastore"
  schema: "arun123"
  tables: []
