---
version: 2
models:
- name: "model_pipeline2_Reformat_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline2_source"
  database: "Tanmay"
  schema: "default"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline2_post_Reformat_1_0"
    tags:
    - "prophecy_temp"
