---
version: 2
models:
- name: "model_pipeline4_WindowFunction_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline4_Filter_1"
  tags:
  - "prophecy_temp"
- name: "model_pipeline4_Intersect_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline4_source"
  database: "hive_metastore"
  schema: "arun123"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline4_post_Filter_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline4_post_Intersect_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_pipeline4_post_WindowFunction_1_0"
    tags:
    - "prophecy_temp"
