name: shared_scala
description: ''
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: sharedscala
  parentArtefactID: sharedteam
  buildSystem: maven
  author: null
  createdAt: '2025-04-10 04:54:37'
pipelines:
  pipelines/dxxcfghvj:
    name: dxxcfghvj
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-04-10 04:54:37'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-04-10 04:54:37'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-04-10T04:54:37.740986Z'
  name: plibMaven
  version: 8.8.2
  id: '316911180'
  createdAt: '2025-04-10T04:54:37.740986Z'
  type: plibMaven
projectDependencies:
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2025-04-10 04:54:26'
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.2.6.1
    isDefault: true
    author: null
    createdAt: '2025-04-10 04:54:26'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
