---
version: 2
models:
- name: "model_p77_Aggregate_1"
  tags:
  - "prophecy_temp"
- name: "model_p77_Deduplicate_1"
  tags:
  - "prophecy_temp"
- name: "model_p77_Join_1"
  tags:
  - "prophecy_temp"
- name: "model_p77_Deduplicate_2"
  tags:
  - "prophecy_temp"
- name: "model_p77_Join_2"
  tags:
  - "prophecy_temp"
- name: "model_p77_WindowFunction_1"
  tags:
  - "prophecy_temp"
- name: "model_p77_Filter_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_p77_source"
  database: "hive_metastore"
  schema: "default"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_p77_post_Aggregate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p77_post_Deduplicate_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p77_post_Deduplicate_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p77_post_Filter_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p77_post_Join_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p77_post_Join_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_p77_post_WindowFunction_1_0"
    tags:
    - "prophecy_temp"
