---
version: 2
models:
- name: "model_pipeline5_Aggregate_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_pipeline5_source"
  database: "hive_metastore"
  schema: "arun123"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_pipeline5_post_Aggregate_1_0"
    tags:
    - "prophecy_temp"
